---
version: '3'
services:
  web:
    build: 
      context: .
      dockerfile: ./Dockerfile
    command: yarn start 
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
      - ./:/home/node/app
    ports:
      - "3000:3000"
    
  postgres:
    container_name: apiBook
    image: postgres:10.5
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=level-acess
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5433:5432'
    volumes:
      - ./volumes/postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin123
    ports:
      - '16543:80'
    depends_on:
      - postgres
    volumes:
      - ./volumes/redis-data:/var/lib/postgresql/data
  

